Repository soywod/himalaya, pull requests merged in 2021-04, with the labels that each got.

#67 Remove unused clap depdenencies
  Cargo.lock
  Cargo.toml
Labels: question

#69 Preview mailboxes with telescope
  vim/autoload/himalaya/mbox.lua
  vim/autoload/himalaya/mbox.vim
  vim/autoload/himalaya/msg.vim
  vim/autoload/himalaya/shared/cli.vim
Labels: enhancement, vim

#53 Make install script POSIX compliant
  README.md
  install.sh
Labels: cli, optimization

#76 Add support for installing using Nix (zero maintenance)
  .gitignore
  .vscode/extensions.json
  .vscode/settings.json
  README.md
  default.nix
  flake.lock
  flake.nix
  shell.nix
Labels: enhancement

#116 handle completions subcommand first
  src/main.rs
Labels: cli, optimization

#132 Refactor table system
  CHANGELOG.md
  Cargo.toml
  README.md
  flake.nix
  src/flag/model.rs
  src/mbox/model.rs
  src/msg/model.rs
  src/table.rs
Labels: cli, optimization
